### ISSUE TITLE
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (default-cli) on project sparkWithJava-chapter04: Command execution failed

### ISSUE THREAD

**Issue by pauldj54** [jgperrin/net.jgp.books.sparkWithJava.ch04#1]
Hi, 
when trying to run the project after imported it withing eclipse with Git Plugin:
- From command line using mvn exe:exec
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (default-cli) on project sparkWithJava-chapter04: Command execution failed
- If I run it as java project from eclipse it worked.

Maybe something missing in the pom.xml file.

**Comment by jgperrin** [comment]
Hey Paul,

Thanks for reporting that. There was indeed a typo in the pom, you can pull it back and execute. 

Thanks again,

jg

**Comment by marciodebarros** [comment]
Hi,

I just pulled the code today and I think there is still a typo on the pom file. The argument for the build is pointing to lab100 and it should be 200 maybe?
