### ISSUE TITLE
Incorrect Class path in pom.xml file

### ISSUE THREAD

**Issue by SinghCoder** [jgperrin/net.jgp.books.sparkWithJava.ch04#4]
Hi, I was reading the book and performing the exercises as given. In chapter 4, where you tell to execute the mvn from command line to analyze Catalyst's activities, the pom.xml file contains invalid classpath for `net.jgp.books.spark.ch04.lab100_transformation_and_action.TransformationAndActionApp`.

It should be lab200 instead of lab100 I guess.

**Comment by marciocg** [comment]
I agree with that.

**Comment by marciocg** [comment]
> Hi, I was reading the book and performing the exercises as given. In chapter 4, where you tell to execute the mvn from command line to analyze Catalyst's activities, the pom.xml file contains invalid classpath for `net.jgp.books.spark.ch04.lab100_transformation_and_action.TransformationAndActionApp`.
> 
> It should be lab200 instead of lab100 I guess.

I agree with that.

**Comment by jgperrin** [comment]
Corrected.
